### 1

In [1]:
from matplotlib import pyplot as plt
import numpy as np 

In [2]:
array = np.array(range(11))
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### 2

In [3]:
array = np.array(np.random.rand(5))
array

array([0.95383074, 0.73123584, 0.73577928, 0.88178525, 0.58025772])

### 3

In [4]:
def sum_values_in_array(array):
    sum_array = sum(v for v in array)
    return sum_array
trois = sum_values_in_array(array)
trois

np.float64(3.8828888298870616)

### 4

In [5]:
array1 = np.array(np.random.rand(5, 1))
array2 = np.array(np.random.rand(1, 5))
def sum_arrays(array1, array2):
    sum_arrays = np.dot(array1, array2)
    return sum_arrays
arrays = sum_arrays(array1, array2)
arrays

array([[0.1477656 , 0.28510558, 0.20982744, 0.37495461, 0.23299605],
       [0.02472428, 0.04770415, 0.03510853, 0.06273777, 0.03898513],
       [0.17300125, 0.33379639, 0.24566213, 0.43898998, 0.27278751],
       [0.13801579, 0.26629387, 0.1959827 , 0.35021451, 0.21762261],
       [0.04891596, 0.09438066, 0.06946077, 0.12412406, 0.07713045]])

### 5

In [6]:
array =  [np.random.randint(1, 5) for i in range(10)]
def unique_in_array(array):
    return np.unique(array)
unique_in_array(array)

array([1, 2, 3, 4])

### 6

In [7]:
def ordered_array(array):
    return np.sort(array)
ordered_array(array)

array([1, 1, 1, 1, 1, 2, 2, 3, 3, 4])

### 7

In [8]:
def mean_array(array):
    return np.mean(array)
mean_array(array)

np.float64(1.9)

### 8

In [9]:
array =  np.array([np.random.randint(1, 10) for i in range(10)])
array
def more_than_five(array):
    return np.where(array > 5, 1, 0)
more_than_five(array)

array([1, 1, 1, 0, 1, 0, 1, 0, 1, 0])

### 9

In [10]:
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

def is_prime_in_array(array):
    vec_func = np.vectorize(is_prime)
    mask = vec_func(array)
    return array[mask]

array =  np.array([np.random.randint(1, 20) for i in range(10)])
print(array)
is_prime_in_array(array)

[15  4  1 13 12  7 14  3 11 14]


array([13,  7,  3, 11])

### 10

In [20]:
arr = np.array([np.random.randint(1, 10) for i in range(9)])
arr_2d = arr.reshape((3,3))
arr_2d

array([[4, 5, 6],
       [1, 8, 2],
       [3, 7, 2]])